### ISSUE TITLE
Linktree Importer

### ISSUE THREAD

**Issue by benkaiser** [aleemrehmtulla/kytelink#10]
Hey @aleemrehmtulla , awesome product! It is very fast and really quite beautiful. Hats off to you!

I wanted to create this issue to gauge interest, would you be open to a pull request to add automatic linktree importing? Allowing users to input a linktree URL and bring across all their links automatically?

**Comment by aleemrehmtulla** [comment]
> Hey @aleemrehmtulla , awesome product! It is very fast and really quite beautiful. Hats off to you!
> 
> I wanted to create this issue to gauge interest, would you be open to a pull request to add automatic linktree importing? Allowing users to input a linktree URL and bring across all their links automatically?

that would be awesome!

**Comment by benkaiser** [comment]
I've published an update to this npm package: https://www.npmjs.com/package/linktree-scraper

Would you like a PR that depends on that, or one that does the direct calls to linktree within kytelink?

**Comment by aleemrehmtulla** [comment]
> I've published an update to this npm package: https://www.npmjs.com/package/linktree-scraper
> 
> Would you like a PR that depends on that, or one that does the direct calls to linktree within kytelink?

def direct calls

planning to do a rehaul feb/march

it'll include scraping other platforms, so best to consolidate them all in one without a bunch of dependencies
