### ISSUE TITLE
Link and icon ok but no text in the button

### ISSUE THREAD

**Issue by jrd10** [aleemrehmtulla/kytelink#11]
Hi Alleem, 
thank you for this nice and hosted open source application.

I opened an account this morning. It was perfect.

Now, no text (just link and icon).

_I am not sure that there is a link, but I create (?) a kyte/jrd10 account :)._

kytelink.com/jrd10
kyte.bio/jrd10

Thank you again, 
José from France.

On Ubuntu 22.04.4 - Wayland - Firefox.
The same with Chrome.

![Screenshot from 2024-02-09 15-16-10](https://github.com/aleemrehmtulla/kytelink/assets/10448655/af52fe26-7cd2-44cb-af6c-c7f791322fe3)

**Comment by aleemrehmtulla** [comment]
> kyte.bio/jrd10

hey - just saw this

the text color is set as white :/

can either set it as black - or default theme 

lmk if you need any help doing so!

- aleem
