### ISSUE TITLE
Teams/Orgs (and Multiple profiles)

### ISSUE THREAD

**Issue by heyakyra** [aleemrehmtulla/kytelink#6]
It is very restrictive to need a separate email address for each profile. It should be possible to create more than one, and to allow other users to have edit-access too.

**Comment by aleemrehmtulla** [comment]
hey kyta! will def add to the board :)

adding multi-user control over a kyte will require a db restructure, but agree how valuable it can be! 

since it's a bigger ticket - not sure when i'll hit it - shouldn't be more then a month thoug

will keep you in the loop with progress :)

**Comment by heyakyra** [comment]
Very cool, filed https://github.com/aleemrehmtulla/kytelink/issues/7 in the meantime. Thanks for working on this! There have been others that have been built and fallen, but nice to see a new open source option rise above the rest

**Comment by heyakyra** [comment]
Ooh, nice! How does one use this? I'm not seeing any options to add users
